### ISSUE TITLE
lua 可以做什么大佬

### ISSUE THREAD

**Issue by 530l** [zincPower/lua_study_2022#1]

**Comment by zincPower** [comment]
Lua 是一种轻量小巧的脚本语言，我们可以在项目中下发 Lua 代码 ，然后项目运行这些 Lua 代码，达到一些动态化的逻辑。
项目需要提前提供一些 api（要足够通用，逻辑的整合就交给 Lua）或是数据类型，Lua 里的代码可以根据业务所需组合出不同的代码逻辑。

举个例子：
例如你做一个相机的应用，你会用到 opengl 来做一些特效的，这时候你可以通过 c 暴露 opengl 给 Lua 调用，下发特效包里面包含着 n 多个 Lua 文件（他们之间有逻辑交互），这些 Lua 文件就是组合使用 gl 的，而这些代码是动态的，随时可更改可下发。
